FROM golang:1.21-alpine3.18
WORKDIR /app
RUN go install github.com/volatiletech/sqlboiler/v4@latest
RUN go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest
COPY sqlboiler.toml .
ENTRYPOINT [ "sqlboiler" ]
